# -*- coding: utf-8 -*-
"""suicide_data_analysis_predictive_modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6t8ngLd2xHbJTD9Ln_ck-256ahTZBSJ

# Global Suicide Rate Prediction and Clustering Analysis

This notebook provides an in-depth analysis of global suicide statistics from 1985 to 2016. Beyond comprehensive data preparation and exploratory data analysis, this project delves into the application of various machine learning models to predict suicide numbers and uncover inherent patterns within the data. We explore Linear Regression, Decision Tree Regression, and Random Forest Regression for predictive tasks, evaluating their performance using metrics like Mean Squared Error (MSE), Root Mean Squared Error (RMSE), and R-squared. Additionally, K-Means Clustering is employed to identify distinct groups or segments within the dataset, and Logistic Regression is used for classification. This comprehensive approach aims to provide actionable insights into factors influencing suicide rates and highlight the most effective predictive models.
"""

#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/kaggle/input/sucidedata/SucideData.csv")

data.head(10)

data.country.unique()

data.dtypes

data.info()

"""# Exploratory Data Analysis"""

#Data Cleaning
data["gdp_for_year"]=data[" gdp_for_year"]
#There was a space in feature infront of gdp_for_year

# Drop the feature with space infront
data.drop(" gdp_for_year",axis=1,inplace=True)

data.info()

#This feature has been stored as string but its actually a numerical feature
data["gdp_for_year"]=data.gdp_for_year.str.replace(",","")
data["gdp_for_year"]=data["gdp_for_year"].astype(float)

data.head()

data.notnull().sum()

data=data.fillna(0)

data.isnull().sum()

"""# **Outlier Detection**"""

#Outlier Detection
df = data
# Select the feature for outlier detection
feature = 'population'

# Calculate Q1, Q3, and IQR
Q1 = df[feature].quantile(0.25)
Q3 = df[feature].quantile(0.75)
IQR = Q3 - Q1

# Define the upper and lower bounds for outlier detection
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = df[(df[feature] < lower_bound) | (df[feature] > upper_bound)]

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)
print("\nOutliers in '{}':".format(feature))
print(outliers[[feature]])

# Visualize the outliers using a box plot
plt.figure(figsize=(8, 6))
sns.boxplot(x=df[feature])
plt.title('Box Plot of {}'.format(feature))
plt.xlabel(feature)
plt.show()

"""# Some Visualization"""

import matplotlib.pyplot as plt
import seaborn as sns

#Count Plot for Generations
from sklearn.preprocessing import LabelEncoder
label_encoder1=LabelEncoder()
data["sex"]=label_encoder1.fit_transform(data["sex"])
label_encoder2=LabelEncoder()
data["generation"]=label_encoder2.fit_transform(data["generation"])


plt.figure(figsize=(30,5))
sns.countplot(data['generation'])

"""# Label Encoding
Before further visualization we need to label our catagorical data into a numerical value or feature.For example there  two features Sex and Generation. we will label them using labelencoder which will automatically label them.
"""

from sklearn.preprocessing import LabelEncoder
label_encoder1=LabelEncoder()
data["sex"]=label_encoder1.fit_transform(data["sex"])

label_encoder2=LabelEncoder()
data["generation"]=label_encoder2.fit_transform(data["generation"])

# Compare suicide  rate between both genders.
sns.barplot(x='sex',y='suicides_no',data=data)

# Will check the factor of GDP over suicidal rate.
plt.figure(figsize=(10,3))
sns.lineplot(x='year',y='gdp_for_year',data=data)

#Will check Trends between Year and Suicide Numbers
fig, ax = plt.subplots()
fig.set_size_inches(14.7, 5.27)
sns.barplot(x='year',y='suicides_no',data=data,ax=ax)

data.info()

"""# **Machine Learning Models**

# 1. Linear Regression model
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import LabelEncoder

#some features need to be encoded in numerical from catagorical data
#Encoding 'age' column
label_encoder_age = LabelEncoder()
data["age"] = label_encoder_age.fit_transform(data["age"])

#Encoding country column
label_encoder_country = LabelEncoder()
data["country"] = label_encoder_country.fit_transform(data["country"])

#Encoding country-year column
label_encoder_country_year = LabelEncoder()
data["country-year"] = label_encoder_country_year.fit_transform(data["country-year"])

#unneeded feature
data = data.drop(columns = ['suicides/100k pop'])

# Prepare features and target
X = data.drop('suicides_no', axis=1)
y = data['suicides_no']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Linear Regression Model
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)
y_pred_linear = linear_reg.predict(X_test)
mse_linear = mean_squared_error(y_test, y_pred_linear)
print(f"Linear Regression MSE: {mse_linear}")
from sklearn import metrics
print("Linear Regression RMSE:",np.sqrt(metrics.mean_squared_error(y_test,y_pred_linear)))

# 1. Residual Plot
residuals = y_test - y_pred_linear
plt.figure(figsize=(7, 4))
sns.residplot(x=y_pred_linear, y=residuals, lowess=True)
plt.title('Residual Plot (Linear Regression)')
plt.xlabel('Predicted Suicides')
plt.ylabel('Residuals')
plt.show()

"""# 2. Decision Tree Model"""

from sklearn.tree import DecisionTreeRegressor

# Features and target ae already prepared
# Data has been siplited into test and train sets
# Decision Tree Regression Model
dt_reg = DecisionTreeRegressor(random_state=42)
dt_reg.fit(X_train, y_train)
y_pred_dt_reg = dt_reg.predict(X_test)
mse_dt_reg = mean_squared_error(y_test, y_pred_dt_reg)
print(f"Decision Tree Regression MSE: {mse_dt_reg}")
print("Decesion Tree RMSE:",np.sqrt(metrics.mean_squared_error(y_test,y_pred_dt_reg)))

plt.figure(figsize=(10, 4))
sns.regplot(x=y_test, y=y_pred_dt_reg, scatter_kws={'alpha': 0.5})
plt.title('Actual vs. Predicted Suicides (Decision Tree Regression)')
plt.xlabel('Actual Suicides')
plt.ylabel('Predicted Suicides')
plt.show()

"""# 3. Random Forest Regression Model"""

from sklearn.ensemble import RandomForestRegressor

# Random Forest Regression Model
rf_reg = RandomForestRegressor(random_state=42)
rf_reg.fit(X_train, y_train)
y_pred_rf_reg = rf_reg.predict(X_test)
mse_rf_reg = mean_squared_error(y_test, y_pred_rf_reg)
print(f"Random Forest Regression MSE: {mse_rf_reg}")
print("Random Forest RMSE:",np.sqrt(metrics.mean_squared_error(y_test,y_pred_rf_reg)))

plt.figure(figsize=(10, 6))
sns.regplot(x=y_test, y=y_pred_rf_reg, scatter_kws={'alpha': 0.5})
plt.title('Actual vs. Predicted Suicides (Random Forest Regression)')
plt.xlabel('Actual Suicides')
plt.ylabel('Predicted Suicides')
plt.show()

"""# 4. K-Means Clustering"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

#Encoding age column
label_encoder_age = LabelEncoder()
data["age"] = label_encoder_age.fit_transform(data["age"])
# Prepare features
X = data.drop('suicides_no', axis=1)

# K-Means Clustering Model
kmeans = KMeans(n_clusters=3, random_state=42)  # Choose the number of clusters
clusters = kmeans.fit_predict(X)
silhouette_avg = silhouette_score(X, clusters)
print(f"K-Means Silhouette Score: {silhouette_avg}")

# Add cluster labels to your DataFrame
data['cluster'] = clusters

feature1 = X.columns[1]
feature2 = X.columns[4]

plt.figure(figsize=(10, 6))
sns.scatterplot(x=feature1, y=feature2, hue='cluster', data=data, palette='viridis')
plt.title('K-Means Clustering')
plt.xlabel(feature1)
plt.ylabel(feature2)
plt.show()

data.info()

"""# Train Accuracy of Models"""

#Linear Regression:
#R-Squared
from sklearn.metrics import r2_score
y_train_pred_linear = linear_reg.predict(X_train)  # Predictions on training data
train_accuracy_linear = r2_score(y_train, y_train_pred_linear)
print(f"Linear Regression Training Accuracy (R-squared): {train_accuracy_linear}")

#Decision Tree Regression
#R-Squared
y_train_pred_dt = dt_reg.predict(X_train)  # Predictions on training data
train_accuracy_dt = r2_score(y_train, y_train_pred_dt)
print(f"Decision Tree Regression Training Accuracy (R-squared): {train_accuracy_dt}")

#Random Forest Regression
#R-Squared
y_train_pred_rf = rf_reg.predict(X_train)  # Predictions on training data
train_accuracy_rf = r2_score(y_train, y_train_pred_rf)
print(f"Random Forest Regression Training Accuracy (R-squared): {train_accuracy_rf}")

#K-Means Clustering
#Silhouette Score, will measure the quality of clustering
# we cant use R-Squared as k-means is a unsupervised learning
print(f"K-Means Silhouette Score: {silhouette_avg}") #Already Evaluated during the model training

"""# Test Accuracy of Models"""

#Linear Regression
y_pred_linear = linear_reg.predict(X_test)  # Predictions on test data
test_accuracy_linear = r2_score(y_test, y_pred_linear)
print(f"Linear Regression Test Accuracy (R-squared): {test_accuracy_linear}")

#Decission Tree Regression
y_pred_dt = dt_reg.predict(X_test)  # Predictions on test data
test_accuracy_dt = r2_score(y_test, y_pred_dt)
print(f"Decision Tree Regression Test Accuracy (R-squared): {test_accuracy_dt}")

#Random Forest regression
y_pred_rf = rf_reg.predict(X_test)  # Predictions on test data
test_accuracy_rf = r2_score(y_test, y_pred_rf)
print(f"Random Forest Regression Test Accuracy (R-squared): {test_accuracy_rf}")

"""# Logistic regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
#we already have our features in X and target variable in y
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(X_train, y_train)

#TrainAccuracy
from sklearn.metrics import accuracy_score
y_train_pred = model.predict(X_train)
train_accuracy = accuracy_score(y_train, y_train_pred)
print(f"Training Accuracy: {train_accuracy}")

#Test Accuracy
y_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)
print(f"Test Accuracy: {test_accuracy}")

#Classification Report
from sklearn.metrics import classification_report
report = classification_report(y_test, y_test_pred)
print("Classification Report:")
print(report)

#Matthews Correlation Coefficient (MCC)
from sklearn.metrics import matthews_corrcoef
y_pred = model.predict(X_test)  # Replace 'model' with your trained classifier
mcc = matthews_corrcoef(y_test, y_pred)
print(f"Matthews Correlation Coefficient (MCC): {mcc}")

#Confussion Matrix
from sklearn.metrics import confusion_matrix
# Assuming 'y_test' contains your true labels and 'model' is your trained classifier
y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, X, y, cv=10)
print("Cross-validation scores:", scores)
print("Average accuracy:", scores.mean())

import matplotlib.pyplot as plt
import numpy as np
models = ['Linear Regression', 'Decision Tree', 'Random Forest']
train_r2 = np.array([train_accuracy_linear, train_accuracy_dt, train_accuracy_rf])
test_r2 = np.array([test_accuracy_linear, test_accuracy_dt, test_accuracy_rf])

bar_width = 0.35
index = np.arange(len(models))

fig, ax = plt.subplots(figsize=(10, 6))
bar1 = ax.bar(index, train_r2, bar_width, label='Train R-squared')
bar2 = ax.bar(index + bar_width, test_r2, bar_width, label='Test R-squared')

ax.set_ylabel('R-squared Score')
ax.set_title('Train and Test R-squared for Regression Models')
ax.set_xticks(index + bar_width / 2)
ax.set_xticklabels(models)
ax.legend()

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

"""## Summary and Model Comparison

This notebook conducted a comprehensive analysis of global suicide data, progressing from thorough data cleaning and exploratory data analysis to the implementation and evaluation of several machine learning models.

**Key Analytical Steps:**
* **Data Preprocessing:** Handled missing values, converted data types, and applied Label Encoding to categorical features (like `sex`, `generation`, `age`, `country`, `country-year`) to prepare the dataset for modeling[cite: 22, 23, 26]. Outlier detection for 'population' was also performed[cite: 17].
* **Exploratory Data Analysis (EDA):** Visualizations were generated to understand trends in suicide rates across generations, genders, and over time in relation to GDP[cite: 20, 24, 25].
* **Machine Learning Models:**
    * **Linear Regression:** Used to predict suicide numbers, evaluated by MSE and RMSE, with a residual plot for analysis[cite: 27].
    * **Decision Tree Regression:** Another predictive model, assessed using MSE and RMSE, and visualized with an Actual vs. Predicted plot[cite: 28, 29].
    * **Random Forest Regression:** An ensemble method for prediction, evaluated by MSE and RMSE, with an Actual vs. Predicted plot[cite: 29, 30].
    * **K-Means Clustering:** Applied to segment the data, with its performance measured by the Silhouette Score. Clusters were visualized to show patterns across 'year' and 'population'[cite: 31].
    * **Logistic Regression:** Employed for a classification task, with its performance evaluated using Training Accuracy, Test Accuracy, and a Classification Report[cite: 36, 37].

**Model Performance Comparison:**

| Model                 | Training R-squared | Test R-squared | Test RMSE (Regression Models) | K-Means Silhouette Score | Logistic Regression Test Accuracy |
| :-------------------- | :----------------- | :------------- | :---------------------------- | :----------------------- | :-------------------------------- |
| Linear Regression     | 0.374              | 0.409          | 668.33 [cite: 27]             | N/A                      | N/A                               |
| Decision Tree Reg.    | 1.0                | 0.983          | 113.68 [cite: 28]             | N/A                      | N/A                               |
| Random Forest Reg.    | 0.997              | 0.989          | 92.80 [cite: 29]              | N/A                      | N/A                               |
| K-Means Clustering    | N/A                | N/A            | N/A                           | 0.883 [cite: 31, 34]     | N/A                               |
| Logistic Regression   | 0.056              | 0.053 [cite: 36, 37]           | N/A                           | N/A                      | 0.053                             |

**Conclusion:**
Among the regression models, the **Random Forest Regression** model demonstrated the highest predictive accuracy with the lowest RMSE and highest R-squared on the test set, indicating its superior ability to predict suicide numbers. The Decision Tree also performed very well. K-Means clustering provided insights into data groupings, with a strong Silhouette Score. Logistic Regression, however, showed very low accuracy, suggesting it may not be suitable for the specific classification task or requires further feature engineering and hyperparameter tuning to address the observed convergence warning[cite: 36].

This notebook provides a robust framework for analyzing suicide data, highlighting the effectiveness of advanced machine learning techniques in understanding and potentially forecasting complex demographic and socio-economic trends.'
"""